import { useEffect, useState } from 'react';
import { NavLink } from 'react-router-dom';
import { ArrowRight, Briefcase, ClipboardCheck, ClipboardList, FileText, GraduationCap, Megaphone, Plus, RefreshCw, ShoppingBag, Users } from 'lucide-react';
import { getAdminDashboard } from '../../../services/adminDashboardService';
import { resolveAssetUrl } from '../../../utils/assetUrl';

const tools = [
  ['Manage user accounts', '/dashboard/admin/users', Users],
  ['SBO positions', '/dashboard/admin/sbo-positions', Briefcase],
  ['Programs and sections', '/dashboard/admin/programs-sections', GraduationCap],
  ['General audit log', '/dashboard/audit-logs', ClipboardCheck],
];
const cards = [
  ['pending_orders', 'Pending Orders', '/dashboard/merchandise/manage-orders', ShoppingBag, 'pending'],
  ['approval_requests', 'Approval Requests', '/dashboard/approvals', ClipboardCheck, 'pending'],
  ['pending_tasks', 'Pending Tasks', '/dashboard/tasks/task-board', ClipboardList, 'pending'],
  ['new_announcements', 'New Announcements', '/dashboard/announcements/view-announcements', Megaphone, 'info'],
];
const money = (value) => `₱${Number(value || 0).toLocaleString('en-PH', { maximumFractionDigits: 0 })}`;

function FinancialMovement({ rows }) {
  const largest = Math.max(1, ...rows.flatMap((row) => [Number(row.income), Number(row.expense)]));
  if (!rows.some((row) => Number(row.income) || Number(row.expense))) return <p className="py-12 text-center text-sm text-slate-500">No ledger transactions in this period.</p>;
  return <div className="mt-5 overflow-x-auto" role="img" aria-label="Monthly ledger income and expenses"><div className="flex h-56 min-w-[360px] items-end gap-3 border-b border-[#DDE7EF] px-1 pb-2 sm:gap-5">{rows.map((row) => <div key={row.month} className="flex min-w-0 flex-1 flex-col items-center"><div className="flex h-44 w-full items-end justify-center gap-1.5 sm:gap-2"><div title={`${row.month} income ${money(row.income)}`} className="w-4 max-w-[32%] rounded-t-lg bg-[#16A34A] sm:w-7" style={{ height: `${Math.max(Number(row.income) ? 4 : 0, Number(row.income) / largest * 100)}%` }} /><div title={`${row.month} expenses ${money(row.expense)}`} className="w-4 max-w-[32%] rounded-t-lg bg-[#DC2626] sm:w-7" style={{ height: `${Math.max(Number(row.expense) ? 4 : 0, Number(row.expense) / largest * 100)}%` }} /></div><span className="mt-2 text-[10px] font-semibold text-slate-600">{new Date(`${row.month}-01T00:00:00`).toLocaleDateString('en', { month: 'short', year: '2-digit' })}</span></div>)}</div><div className="mt-3 flex flex-wrap gap-4 text-xs font-semibold text-slate-600"><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-[#16A34A]" />Income</span><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-[#DC2626]" />Expenses</span></div><table className="sr-only"><caption>Monthly financial movement</caption><thead><tr><th>Month</th><th>Income</th><th>Expenses</th></tr></thead><tbody>{rows.map((row) => <tr key={row.month}><td>{row.month}</td><td>{money(row.income)}</td><td>{money(row.expense)}</td></tr>)}</tbody></table></div>;
}

export default function AdminHomePage() {
  const [months, setMonths] = useState(6);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [reload, setReload] = useState(0);
  useEffect(() => {
    let active = true;
    setLoading(true); setError('');
    getAdminDashboard(months).then((response) => { if (active) setData(response.data); }).catch(() => { if (active) setError('Dashboard updates could not be loaded.'); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [months, reload]);

  return <div className="space-y-5">
    {error && <div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span>{error}</span><button type="button" onClick={() => setReload((value) => value + 1)} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-red-200 bg-white px-4 font-bold"><RefreshCw size={15} /> Try again</button></div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Administration summary">{cards.map(([key, label, to, Icon, tone]) => <NavLink key={key} to={to} className="group rounded-3xl border border-[#DDE7EF] bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className={`status-icon status-${tone}`}><Icon size={20} /></span><ArrowRight size={16} className="text-slate-400 group-hover:text-[#0878B7]" /></div><p className="mt-4 text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-black tabular-nums text-[#0F172A]">{loading ? '…' : error ? '—' : Number(data?.counts?.[key] ?? 0).toLocaleString()}</p></NavLink>)}</section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-5"><section className="rounded-3xl border border-[#DDE7EF] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-extrabold">Financial status</h2><p className="mt-1 text-xs text-slate-500">Monthly income and expenses from the organization ledger.</p></div><label className="text-xs font-bold text-slate-600">Period<select aria-label="Financial status period" value={months} onChange={(event) => setMonths(Number(event.target.value))} className="mt-1 block rounded-xl px-3 text-sm"><option value={3}>3 months</option><option value={6}>6 months</option><option value={12}>12 months</option></select></label></div>{loading ? <div role="status" className="mt-5 h-56 animate-pulse rounded-2xl bg-slate-100"><span className="sr-only">Loading financial status</span></div> : error ? <p className="py-12 text-center text-sm text-red-700">Financial data is unavailable.</p> : <FinancialMovement rows={data?.movement || []} />}<NavLink to="/dashboard/finance/financial-ledger" className="mt-4 inline-flex min-h-11 items-center gap-1 text-xs font-bold text-[#0878B7] hover:underline">Open digital ledger <ArrowRight size={14} /></NavLink></section><section className="overflow-hidden rounded-3xl border border-[#DDE7EF] bg-white shadow-sm"><div className="border-b border-[#DDE7EF] p-5"><h2 className="text-base font-extrabold">Administration workspace</h2><p className="mt-1 text-xs text-slate-500">Manage organization records and access.</p></div><div className="grid sm:grid-cols-2">{tools.map(([label, to, Icon]) => <NavLink key={to} to={to} className="flex min-h-20 items-center gap-3 border-b border-[#DDE7EF] p-4 hover:bg-[#F8FBFD]"><span className="status-icon status-info"><Icon size={18} /></span><span className="min-w-0 flex-1 text-sm font-bold">{label}</span><ArrowRight size={15} className="text-slate-400" /></NavLink>)}</div></section></div>
      <aside className="rounded-3xl border border-[#DDE7EF] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#0878B7]">Latest updates</p><h2 className="mt-1 text-base font-extrabold">Announcements</h2></div><span className="status-icon status-info"><Megaphone size={19} /></span></div>{loading ? <div className="mt-5 h-44 animate-pulse rounded-2xl bg-slate-100" /> : error ? <p className="py-8 text-sm text-red-700">Announcements are unavailable.</p> : data?.announcements?.length ? <div className="mt-4 space-y-3">{data.announcements.map((post) => <article key={post.id} className="rounded-2xl border border-[#DDE7EF] p-4"><div className="flex items-center gap-2"><span className="status-icon status-info !h-9 !w-9"><Megaphone size={16} /></span><div className="min-w-0"><p className="truncate text-xs font-bold">{post.source_organization?.name || 'HIUSA'}</p><p className="text-[11px] text-slate-500">{[post.creator && `${post.creator.first_name} ${post.creator.last_name}`, post.published_at && new Date(post.published_at).toLocaleDateString()].filter(Boolean).join(' · ')}</p></div></div><h3 className="mt-3 text-sm font-bold">{post.title}</h3><p className="mt-1 line-clamp-3 text-xs leading-5 text-slate-600">{post.body}</p>{post.image_url && <img src={resolveAssetUrl(post.image_url)} alt="" loading="lazy" className="mt-3 max-h-28 w-full rounded-xl object-cover" />}</article>)}</div> : <p className="py-8 text-sm text-slate-500">No published announcements yet.</p>}<div className="mt-4 grid gap-2"><NavLink to="/dashboard/announcements/create-announcement" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[#0878B7] px-4 text-sm font-bold text-white"><Plus size={16} /> Create Announcement</NavLink><NavLink to="/dashboard/announcements/manage-announcements" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[#DDE7EF] px-4 text-sm font-bold"><FileText size={16} /> Manage Announcements</NavLink><NavLink to="/dashboard/announcements/view-announcements" className="inline-flex min-h-11 items-center justify-center gap-2 text-sm font-bold text-[#0878B7]">View Feed <ArrowRight size={15} /></NavLink></div></aside></div>
  </div>;
}
