import { useEffect, useMemo, useState } from 'react';
import { Clock3, Eye, Search, ShieldCheck, X } from 'lucide-react';
import PaginationControls from '../../../components/PaginationControls';
import { getAuditLogs } from '../../../services/financeService';

const EMPTY_FILTERS = { search: '', module: '', category: '', role: '', department: '', program: '', from: '', to: '', sort: 'newest', per_page: 25 };

export default function GeneralAuditLogPage() {
  const [logs, setLogs] = useState([]);
  const [filters, setFilters] = useState(EMPTY_FILTERS);
  const [page, setPage] = useState(1);
  const [meta, setMeta] = useState({ total: 0, per_page: 25, current_page: 1 });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedLog, setSelectedLog] = useState(null);

  useEffect(() => {
    let cancelled = false;
    const timer = setTimeout(async () => {
      setLoading(true); setError('');
      try {
        const response = await getAuditLogs({ ...filters, page }); const payload = response.data;
        if (!cancelled) { setLogs(payload.data || []); setMeta({ total: payload.total || 0, per_page: payload.per_page || filters.per_page, current_page: payload.current_page || page }); }
      } catch { if (!cancelled) setError('Unable to load the General Audit Log.'); }
      finally { if (!cancelled) setLoading(false); }
    }, 250);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [filters, page]);

  const update = (key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const departments = useMemo(() => [...new Set(logs.map((log) => log.actor?.department).filter(Boolean))], [logs]);
  const programs = useMemo(() => [...new Set(logs.map((log) => log.actor?.program).filter(Boolean))], [logs]);

  return <div className="space-y-5">
    <section className="rounded-xl border border-[#DDE7EF] bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-[#EEF6FB] text-[#0B8ED0]"><ShieldCheck size={21} /></span><div><p className="text-[10px] font-bold uppercase tracking-widest text-[#0B8ED0]">System-wide history</p><h1 className="mt-1 text-2xl font-black text-[#0F172A]">General Audit Log</h1><p className="mt-1 text-sm text-slate-500">Trace actors, records, academic context, approvals, payments, and before/after values across HIUSA.</p></div></div></section>

    <section className="rounded-xl border border-[#DDE7EF] bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">
      <label className="relative md:col-span-2"><span className="sr-only">Search audit activity</span><Search size={16} className="absolute left-3 top-3.5 text-slate-400" /><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder="Search actor, action, module, or record ID..." className="h-11 w-full rounded-lg border border-[#DDE7EF] pl-9 pr-3 text-sm outline-none focus:border-[#0B8ED0]" /></label>
      <select aria-label="Module" value={filters.module} onChange={(event) => update('module', event.target.value)} className="h-11 rounded-lg border border-[#DDE7EF] px-3 text-sm"><option value="">All modules</option>{['users', 'orders', 'merchandise', 'invoices', 'transactions', 'budgets', 'events', 'tasks', 'collections', 'attendance', 'elections', 'announcements', 'academic_structure'].map((module) => <option key={module} value={module}>{module.replaceAll('_', ' ')}</option>)}</select>
      <select aria-label="Action category" value={filters.category} onChange={(event) => update('category', event.target.value)} className="h-11 rounded-lg border border-[#DDE7EF] px-3 text-sm"><option value="">All actions</option>{['CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', 'PAYMENT', 'COLLECTION', 'REMITTANCE', 'ATTENDANCE', 'STATUS_CHANGE'].map((category) => <option key={category}>{category}</option>)}</select>
      <select aria-label="Actor role" value={filters.role} onChange={(event) => update('role', event.target.value)} className="h-11 rounded-lg border border-[#DDE7EF] px-3 text-sm"><option value="">All actor roles</option>{['ADMIN', 'SBO_OFFICER', 'DEPARTMENT_HEAD', 'STUDENT'].map((role) => <option key={role}>{role}</option>)}</select>
      <select aria-label="Actor department" value={filters.department} onChange={(event) => update('department', event.target.value)} className="h-11 rounded-lg border border-[#DDE7EF] px-3 text-sm"><option value="">All departments</option>{departments.map((value) => <option key={value}>{value}</option>)}</select>
      <select aria-label="Actor program" value={filters.program} onChange={(event) => update('program', event.target.value)} className="h-11 rounded-lg border border-[#DDE7EF] px-3 text-sm"><option value="">All programs</option>{programs.map((value) => <option key={value}>{value}</option>)}</select>
      <label className="text-[10px] font-bold uppercase text-slate-500">From<input type="date" value={filters.from} onChange={(event) => update('from', event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#DDE7EF] px-2 text-xs" /></label>
      <label className="text-[10px] font-bold uppercase text-slate-500">To<input type="date" value={filters.to} onChange={(event) => update('to', event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#DDE7EF] px-2 text-xs" /></label>
      <select aria-label="Sort audit logs" value={filters.sort} onChange={(event) => update('sort', event.target.value)} className="h-11 rounded-lg border border-[#DDE7EF] px-3 text-sm"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="user">User name</option><option value="role">User role</option><option value="module">Module</option><option value="action">Action</option></select>
      <select aria-label="Audit rows per page" value={filters.per_page} onChange={(event) => update('per_page', Number(event.target.value))} className="h-11 rounded-lg border border-[#DDE7EF] px-3 text-sm">{[10, 25, 50, 100].map((value) => <option key={value} value={value}>{value} rows</option>)}</select>
      <button type="button" onClick={() => { setFilters(EMPTY_FILTERS); setPage(1); }} className="h-11 rounded-lg border border-[#DDE7EF] px-3 text-xs font-bold text-[#0B8ED0]">Clear filters</button>
    </div></section>

    {error && <p className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
    <section className="overflow-hidden rounded-xl border border-[#DDE7EF] bg-white shadow-sm">
      {loading ? <div className="space-y-3 p-5">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-24 animate-pulse rounded-lg bg-slate-100" />)}</div> : logs.length === 0 ? <div className="p-12 text-center"><Clock3 size={34} className="mx-auto text-slate-300" /><p className="mt-3 text-sm font-bold text-slate-600">No audit activity matches these filters.</p></div> : <div className="divide-y divide-[#E5EDF3]">{logs.map((log) => <article key={log.id} className="p-4 transition hover:bg-[#F8FBFD] sm:p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#EEF6FB] px-2.5 py-1 text-[10px] font-bold uppercase text-[#0B8ED0]">{log.module_label || log.module}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold uppercase text-slate-600">{log.action_category}</span><span className="font-mono text-[10px] text-slate-400">LOG-{log.id} · Record {log.record_id}</span></div><h2 className="mt-2 text-sm font-bold leading-6 text-[#0F172A] sm:text-base">{log.description}</h2><p className="mt-1 text-xs text-slate-500">Performed by <strong className="text-slate-700">{log.actor?.name || 'System'}</strong>{log.actor?.role ? ` · ${log.actor.role.replaceAll('_', ' ')}` : ''}{log.actor?.position_title ? ` · ${log.actor.position_title}` : ''}</p>{log.actor?.department && <p className="mt-1 text-xs text-slate-400">Actor profile: {[log.actor.department, log.actor.program, log.actor.year_level, log.actor.section].filter(Boolean).join(' · ')}</p>}{log.affected_user && <p className="mt-1 text-xs text-slate-400">Affected: {log.affected_user.name} · {[log.affected_user.department, log.affected_user.program, log.affected_user.year_level, log.affected_user.section].filter(Boolean).join(' · ') || 'No academic details'}</p>}</div><div className="shrink-0 text-right"><time className="block text-xs font-medium text-slate-400">{log.created_at ? new Date(log.created_at).toLocaleString('en-PH') : 'Unknown time'}</time><button type="button" onClick={() => setSelectedLog(log)} className="mt-2 inline-flex items-center gap-1 rounded-md border border-[#DDE7EF] px-2 py-1 text-[10px] font-bold text-[#0B8ED0]"><Eye size={12} />View details</button></div></div>{log.changes?.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{log.changes.slice(0, 4).map((change) => <span key={change.field} className="rounded-md border border-[#DDE7EF] bg-white px-2 py-1 text-[10px] font-semibold text-slate-500">{change.field}: {change.to}</span>)}</div>}</article>)}</div>}
      <PaginationControls currentPage={meta.current_page} totalItems={meta.total} pageSize={meta.per_page} onPageChange={setPage} label="audit records" />
    </section>

    {selectedLog && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-[#0B1831]/55 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-5 shadow-2xl"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-bold uppercase text-[#0B8ED0]">Audit record LOG-{selectedLog.id}</p><h2 className="mt-1 text-xl font-black text-[#0F172A]">{selectedLog.description}</h2><p className="mt-1 text-xs text-slate-500">{selectedLog.module_label} · {selectedLog.action_label} · {new Date(selectedLog.created_at).toLocaleString('en-PH')}</p></div><button type="button" aria-label="Close audit details" onClick={() => setSelectedLog(null)} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-[#EEF6FB]"><X size={18} /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Actor', selectedLog.actor?.name], ['Actor role / position', [selectedLog.actor?.role?.replaceAll('_', ' '), selectedLog.actor?.position_title].filter(Boolean).join(' · ')], ['Actor academic profile', [selectedLog.actor?.department, selectedLog.actor?.program, selectedLog.actor?.major, selectedLog.actor?.year_level, selectedLog.actor?.section].filter(Boolean).join(' · ')], ['Affected record', selectedLog.subject], ['Record type', selectedLog.record_type], ['Record ID', selectedLog.record_id], ['IP address', selectedLog.ip_address], ['Timestamp', new Date(selectedLog.created_at).toLocaleString('en-PH')]].map(([label, value]) => <div key={label} className="rounded-lg border border-[#DDE7EF] bg-[#F8FBFD] p-3"><p className="text-[10px] font-bold uppercase text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value || '-'}</p></div>)}</div><div className="mt-4"><h3 className="text-sm font-bold">Before / after changes</h3>{selectedLog.changes?.length ? <div className="mt-2 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead className="bg-[#F8FBFD]"><tr><th className="px-3 py-2">Field</th><th className="px-3 py-2">Before</th><th className="px-3 py-2">After</th></tr></thead><tbody className="divide-y divide-[#E5EDF3]">{selectedLog.changes.map((change) => <tr key={change.field}><td className="px-3 py-2 font-bold">{change.field}</td><td className="px-3 py-2 text-slate-500">{change.from || '-'}</td><td className="px-3 py-2 text-[#0F172A]">{change.to}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-xs text-slate-400">No field-level change payload was recorded for this action.</p>}</div></div></div>}
  </div>;
}
