import { useEffect, useState } from 'react';
import { Plus } from 'lucide-react';
import { createSboPosition, getSboPositions } from '../../../services/userService';

export default function ManageSboPositionsPage() {
  const [positions, setPositions] = useState([]); const [form, setForm] = useState({ title: '', description: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async () => { try { setPositions(await getSboPositions()); } catch { setError('Unable to load SBO positions.'); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await createSboPosition({ title: form.title.trim(), description: form.description.trim() || null }); setForm({ title: '', description: '' }); await load(); } catch (err) { setError(err.response?.data?.message || 'Unable to create position.'); } finally { setBusy(false); } };
  return <div className="space-y-5"><section className="rounded-xl border border-[#DDE7EF] bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-widest text-[#0B8ED0]">Organization roles</p><h2 className="mt-1 text-2xl font-black text-[#0F172A]">Manage SBO Positions</h2><p className="mt-1 text-sm text-slate-500">Define each position and its responsibilities before assigning it to an SBO Officer.</p><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Position title<input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} required placeholder="e.g. Logistics Coordinator" className="mt-1.5 h-11 w-full rounded-lg border border-[#DDE7EF] px-3 text-sm" /></label><label className="text-sm font-semibold">Responsibilities / job description<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} placeholder="Describe what this officer is responsible for in task management." className="mt-1.5 min-h-24 w-full rounded-lg border border-[#DDE7EF] p-3 text-sm" /></label><button disabled={busy || !form.title.trim()} className="flex h-11 w-fit items-center gap-2 rounded-lg bg-[#0B8ED0] px-4 text-sm font-bold text-white disabled:opacity-50"><Plus size={16}/>{busy?'Creating…':'Create Position'}</button></form>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</section><section className="rounded-xl border border-[#DDE7EF] bg-white shadow-sm"><div className="border-b border-[#DDE7EF] p-5"><h3 className="font-bold">Available SBO Positions</h3></div><div className="divide-y divide-[#E5EDF3]">{positions.length ? positions.map((position)=><div key={position.id} className="p-5"><p className="font-bold text-[#0F172A]">{position.title}</p><p className="mt-1 text-sm text-slate-500">{position.description || 'No responsibilities recorded yet.'}</p></div>) : <p className="p-8 text-center text-sm text-slate-400">No SBO positions have been created.</p>}</div></section></div>;
}
